# This action runs on a local github runner
# See https://jano.dev/programming/2022/04/15/local-spm-ga.html

# To install xcbeautify run:
# brew install ruby
# echo 'export PATH="/opt/homebrew/opt/ruby/bin:$PATH"' >> ~/.zshrc
# brew install xcbeautify

name: Swift
on: [push]
jobs:
  ios-latest:
    name: Unit Tests (iOS 18.2, Xcode 16.2)
    runs-on: [self-hosted]
    env: 
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Generate project
        run: |
          brew install tuist        
          tuist generate --no-open
      - name: Build iOS
        run: |
          set -o pipefail && xcodebuild build -scheme "CoreDataStack" -destination "OS=18.2,name=iPhone 16 Pro" -skipPackagePluginValidation | xcbeautify
      - name: Build macOS
        run: |
          set -o pipefail && xcodebuild build -scheme "CoreDataStack" -destination "platform=macOS,arch=arm64" -skipPackagePluginValidation | xcbeautify
